[[redirects]]
  from = "/"
  to = "https://kazarbuild.netlify.app/%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5%20%D0%BA%D0%B0%D1%80%D1%82%D1%8B%20%D0%BF%D0%BE%20%D1%80%D0%B5%D0%BC%D0%BE%D0%BD%D1%82%D1%83,%D0%BC%D0%B5%D0%BD%D1%8E/translate"
  status = 200
